exports.defaultCategories = [
    { name: 'Rent', type: 'expense' },
    { name: 'Utilities', type: 'expense' },
    { name: 'Groceries', type: 'expense' },
    { name: 'Entertainment', type: 'expense' },
    { name: 'Transportation', type: 'expense' },
    { name: 'Salary', type: 'income' },
    { name: 'Investment income', type: 'income' },
    { name: 'Freelance work', type: 'income' },
    { name: 'Stock market investments', type: 'investment' },
    { name: 'Real estate investments', type: 'investment' },
    { name: 'Bonds', type: 'investment' },
    { name: 'Mutual funds', type: 'investment' },
    { name: 'Certificates of deposit', type: 'investment' },
    { name: 'Retirement accounts', type: 'investment' },
    { name: 'Hedge funds', type: 'investment' },
    { name: 'Private equity', type: 'investment' },
    { name: 'Venture capital', type: 'investment' },
    { name: 'Commodities', type: 'investment' },
    { name: 'Cryptocurrency', type: 'investment' },
    { name: 'Other', type: 'other' },
];